# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TIuc1DnT4venNpicDEegRs2EJFwXDc4_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

# read in the "financial analytics file" as a pandas dataframe
Data = pd.read_csv('/content/Financial Analytics data.csv')

# Take a brief look at the data
Data.tail()





Data.shape

Data.index

Data.columns

Data.info()

# Verify and clean column names
Data.columns = Data.columns.str.strip()
Data = Data.rename(columns={
    'Serial NumberName': 'Serial Number',
    'Name of Company': 'Name of Company',
    'Mar Cap – Crore': 'Mar Cap - Crore',
    'Sales Qtr – Crore': 'Sales Qtr - Crore'
})

# Clean the data
Data_cleaned = Data.dropna(subset=['Mar Cap - Crore', 'Sales Qtr - Crore'])
Data_cleaned['Mar Cap - Crore'] = Data_cleaned['Mar Cap - Crore'].astype(float)
Data_cleaned['Sales Qtr - Crore'] = Data_cleaned['Sales Qtr - Crore'].astype(float)

"""Key Metrics Identification:

Market Capitalization (Mar Cap):
Top companies by market cap.
Distribution of market cap across all companies.
Quarterly Sales (Sales Qtr):
Top companies by quarterly sales.
Distribution of quarterly sales.
Correlation Analysis:
Relationship between market cap and quarterly sales.
Outliers:
Identify companies with significantly high market cap or sales.
"""

### 1. Key Metrics Identification

# Top Companies by Market Cap
top_market_cap = Data_cleaned.nlargest(10, 'Mar Cap - Crore')
top_market_cap.to_csv('Top_Market_Cap.csv', index=False)

plt.figure(figsize=(10, 6))
sns.barplot(data=top_market_cap, x='Mar Cap - Crore', y='Name')
plt.title('Top 10 Companies by Market Cap')
plt.xlabel('Market Cap (Crores)')
plt.ylabel('Company')
plt.tight_layout()
plt.savefig('top_market_cap.png')
# plt.clf()

# Top Companies by Quarterly Sales
top_quarterly_sales = Data_cleaned.nlargest(10, 'Sales Qtr - Crore')
top_quarterly_sales.to_csv('Top_Quarterly_Sales.csv', index=False)

plt.figure(figsize=(10, 6))
sns.barplot(data=top_quarterly_sales, x='Sales Qtr - Crore', y='Name')
plt.title('Top 10 Companies by Quarterly Sales')
plt.xlabel('Quarterly Sales (Crores)')
plt.ylabel('Company')
plt.tight_layout()
# plt.savefig('top_quarterly_sales.png')
# plt.clf()
plt.show()

# Descriptive Statistics
desc_stats = Data_cleaned[['Mar Cap - Crore', 'Sales Qtr - Crore']].describe()
desc_stats.to_csv('Descriptive_Statistics.csv')

"""Factor Analysis:

Sector-wise Comparison:
If sector data is available, analyze market cap and sales across different sectors.
Clustering:
Group companies based on similar characteristics (e.g., market cap and sales)
"""

# Outlier Detection
Data_cleaned['Market Cap Outlier'] = Data_cleaned['Mar Cap - Crore'] > Data_cleaned['Mar Cap - Crore'].quantile(0.95)
Data_cleaned['Sales Outlier'] = Data_cleaned['Sales Qtr - Crore'] > Data_cleaned['Sales Qtr - Crore'].quantile(0.95)

plt.figure(figsize=(10, 6))
sns.scatterplot(data=Data_cleaned, x='Mar Cap - Crore', y='Sales Qtr - Crore', style='Market Cap Outlier', hue='Sales Outlier')
plt.title('Market Cap vs Quarterly Sales (Outliers Highlighted)')
plt.xlabel('Market Cap (Crores)')
plt.ylabel('Quarterly Sales (Crores)')
plt.tight_layout()
plt.savefig('market_cap_vs_sales_outliers.png')
# plt.clf()

# Clustering Analysis
kmeans = KMeans(n_clusters=3, random_state=42)
Data_cleaned['Cluster'] = kmeans.fit_predict(Data_cleaned[['Mar Cap - Crore', 'Sales Qtr - Crore']])

Data_cleaned.to_csv('Clustered_Data.csv', index=False)

plt.figure(figsize=(10, 6))
sns.scatterplot(data=Data_cleaned, x='Mar Cap - Crore', y='Sales Qtr - Crore', hue='Cluster')
plt.title('Market Cap vs Quarterly Sales (with Clusters)')
plt.xlabel('Market Cap (Crores)')
plt.ylabel('Quarterly Sales (Crores)')
plt.tight_layout()
plt.savefig('market_cap_vs_sales_with_clusters.png')
# plt.clf()

plt.figure(figsize=(10, 6))
plt.pie(Data_cleaned['Cluster'].value_counts(), labels=Data_cleaned['Cluster'].value_counts().index, autopct='%1.1f%%')
plt.title('Distribution of Clusters')
plt.tight_layout()
plt.savefig('clusters_distribution.png')
# plt.clf()

"""Meaningful Relationships:

Correlation Heatmap:
Visualize relationships between numerical attributes.
Scatter Plots:
Visualize the relationship between market cap and quarterly sales
"""

# Correlation Analysis
correlation = Data_cleaned[['Mar Cap - Crore', 'Sales Qtr - Crore']].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.savefig('correlation_heatmap.png')
# plt.clf()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=Data_cleaned, x='Mar Cap - Crore', y='Sales Qtr - Crore')
plt.title('Market Cap vs Quarterly Sales')
plt.xlabel('Market Cap (Crores)')
plt.ylabel('Quarterly Sales (Crores)')
plt.tight_layout()
plt.savefig('market_cap_vs_sales.png')
# plt.clf()